kind: PersistentVolume
apiVersion: v1
metadata:
  name: apicuriodb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/opt/volume/apicurio"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apicuriodata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: manual
